### ISSUE TITLE
Need of NuGet 

### ISSUE THREAD

**Issue by Yxno67** [RSE-Telecom-ICT/Upload-AutopilotInfo-To-Blob#4]
https://github.com/RSE-Telecom-ICT/Upload-AutopilotInfo-To-Blob/blob/e088221e48b98e93746dd97a7e7936180cef126c/hash-upload-partner.ps1#L10

Hi, i am new to scripting and powershell so forgive me if this is a n00b question, but do we need the part where it is checking for NuGet in the script Get-WindowsAutoPilotInfo.ps1 and there it is already part of the script so i thought if you ran it, it will check (and install if not installed) for NuGet anyways? 

I am just trying to learn and understand, ty

**Comment by BJD1997** [comment]
Hi Yuno,

I had to start somewhere as well so there is no stupid question :)

The script needs to be resiliant and robust so I need to prepare for situations where things aren't in place.
I've looked up the Get-WindowsAutopilotInfo.ps1 and looks like they added the Nuget install in the script (version 3.5).

I've done some quick testing on a VM which didnt have Nuget Installed and tried to install the Get-WindowsAutoPilot.ps1 script.
When running that command it asks if I want to install the NuGet provider

`NuGet provider is required to continue
PowerShellGet requires NuGet provider version '2.8.5.201' or newer to interact with NuGet-based repositories. The NuGet
 provider must be available in 'C:\Program Files\PackageManagement\ProviderAssemblies' or
'C:\Users\User\AppData\Local\PackageManagement\ProviderAssemblies'. You can also install the NuGet provider by
running 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'. Do you want PowerShellGet to install
and import the NuGet provider now?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):`

This is why I included the check and handle the install in my script.
Since I can't provide any input when my script is ran trough an RMM agent.

I'm not saying my approach is perfect other powershell guru's can obviously improve on my attempt.

**Comment by Yxno67** [comment]
Wow thank you for the fast reply ! Yea that makes absolutley sense - so i get that `Find-PackageProvider -Name NuGet -ForceBootstrap -IncludeDependencies` is not enough in this case and we need `Install-PackageProvider` with `-Force` . 
Thank you and have a great day!
